##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## (C) Copyright 2018-2019 Modeling Value Group B.V. (http://modelingvalue.org)                                        ~
##                                                                                                                     ~
## Licensed under the GNU Lesser General Public License v3.0 (the 'License'). You may not use this file except in      ~
## compliance with the License. You may obtain a copy of the License at: https://choosealicense.com/licenses/lgpl-3.0  ~
## Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on ~
## an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the  ~
## specific language governing permissions and limitations under the License.                                          ~
##                                                                                                                     ~
## Maintainers:                                                                                                        ~
##     Wim Bast, Tom Brus, Ronald Krijgsheld                                                                           ~
## Contributors:                                                                                                       ~
##     Arjan Kok, Carel Bast                                                                                           ~
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: 'template-action'
description: 'template for github action'
author: 'Tom Brus'

inputs:
  token:
    description: 'github token'
    required: true
  message:
    description: 'a name of somebody'
    required: true
  trace:
    description: 'set this to "true" if you would like bash-tracing'
    required: false
    default: "false"

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        set -euo pipefail

        if [[ "${INPUT_TRACE:-false}" == "true" ]]; then
          for name in $(env | grep '^INPUT_' | sed 's/^INPUT_//;s/=.*//' | sort); do
            printf "# %16s = %s\n" "$name" "$(eval "echo \${INPUT_$name:-}")"
          done
          set -x
        fi

        . "${{ github.action_path }}/buildtoolsMeme.sh" "$INPUT_TOKEN"
        . "${{ github.action_path }}/functions.sh"

        main \
          "$INPUT_TOKEN" \
          "$INPUT_MESSAGE"
