name: test
on:
  push
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get generic info"
        uses: ModelingValueGroup/generic-info@master

      - name: "get buildtools"
        uses: ModelingValueGroup/buildtools@master

      - name: "(re)generate some files"
        run: |
          . <(java -jar ~/buildtools.jar)
          correctEols
          correctHeaders header

      - name: "test local"
        run: |
          set -euo pipefail
          . <(java -jar ~/buildtools.jar)
          . functions.sh
          e="::set-output name=response::I agree with plugh or xyzzy%0Aand again: I agree with plugh or xyzzy%0A"
          o="$(main "plugh or xyzzy")"
          if [[ "$o" != "$e" ]]; then
            echo "expected: $e"
            echo "found   : $o"
            exit 45
          fi

      - name: "test as action"
        id: teststep
        uses: ModelingValueGroup/template-action@master
        with:
          message: hi
          trace: true

      - name: "check output"
        run: |
          e="$(printf "%s\n%s\n" "I agree with hi" "and again: I agree with hi")"
          o="$(printf "%s\n"     "${{steps.teststep.outputs.response}}")"
          if [[ "$o" != "$e" ]]; then
            echo "expected: $e"
            echo "found   : $o"
            exit 45
          fi

      - name: "push changes back to github"
        run: |
          . <(java -jar ~/buildtools.jar)
          pushBackToGithub "${{ secrets.GITHUB_TOKEN }}" "automation@modelingvalue.com" "adjusted files [by github actions]"

