name: test
on:
  push
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get generic info"
        uses: ModelingValueGroup/generic-info@master

      - name: "get buildtools"
        uses: ModelingValueGroup/buildtools@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "(re)generate some files"
        run: |
          . <(java -jar ~/buildtools.jar)
          correctEols
          correctHeaders header

      - name: "test local"
        run: |
          set -euo pipefail
          set -x
          . <(java -jar ~/buildtools.jar)
          . functions.sh
          e="::set-output name=response::I agree with plugh or xyzzy%0Aand again: I agree with plugh or xyzzy%0A"
          o="$(main "plugh or xyzzy")"
          if [[ "$o" != "$e" ]]; then
            echo "expected: $e"
            echo "found   : $o"
            exit 45
          fi

      - name: "test as action 1"
        id: teststep1
        uses: ModelingValueGroup/template-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: hi
          trace: true

      - name: "check output 1"
        run: |
          e="$(printf "%s\n%s\n" "I agree with hi" "and again: I agree with hi")"
          o="$(printf "%s\n"     "${{steps.teststep1.outputs.response}}")"
          hexdump -C <<<"$e"
          hexdump -C <<<"$o"
          if [[ "$o" != "$e" ]]; then
            echo "expected: $e"
            echo "found   : $o"
            exit 45
          fi

      - name: "test as action 2"
        id: teststep2
        uses: ModelingValueGroup/template-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 27%
          trace: true

      - name: "check output 2"
        run: |
          e="$(printf "%s\n%s\n" "I agree with 27%" "and again: I agree with 27%")"
          o="$(printf "%s\n"     "${{steps.teststep2.outputs.response}}")"
          hexdump -C <<<"$e"
          hexdump -C <<<"$o"
          if [[ "$o" != "$e" ]]; then
            echo "expected: $e"
            echo "found   : $o"
            exit 45
          fi

      - name: "push changes back to github"
        run: |
          . <(java -jar ~/buildtools.jar)
          pushBackToGithub "${{ secrets.GITHUB_TOKEN }}" "automation@modelingvalue.com" "adjusted files [by github actions]"

